In [32]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Display settings used by professionals
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 30)
pd.set_option('display.float_format', '{:.2f}'.format)

print(f"pandas {pd.__version__}  |  numpy {np.__version__}  ✅")

pandas 3.0.3  |  numpy 2.4.6  ✅

In [33]:
df_immovlan = pd.read_csv("../data/raw/properties_cleaned.csv")
print(type(df_immovlan))

<class 'pandas.DataFrame'>

In [34]:
# Shape
print("Shape:", df_immovlan.shape)
print(f"{df_immovlan.shape[0]:,} rows × {df_immovlan.shape[1]} columns\n")

Shape: (11501, 34)
11,501 rows × 34 columns

In [35]:
# dtypes + non-null counts
df_immovlan.info()

<class 'pandas.DataFrame'>
RangeIndex: 11501 entries, 0 to 11500
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_id                 11501 non-null  str
 1   property_type               11501 non-null  str
 2   property_subtype            11501 non-null  str
 3   price                       11292 non-null  float64
 4   price_type                  11501 non-null  str
 5   living_area_m2              10707 non-null  float64
 6   bedrooms                    11090 non-null  float64
 7   bathrooms                   10203 non-null  float64
 8   address                     9299 non-null   str
 9   postal_code                 11501 non-null  int64
 10  city                        11501 non-null  str
 11  latitude                    11499 non-null  float64
 12  longitude                   11499 non-null  float64
 13  building_year               6790 non-null   float64
 14  state_of_the_building       8819 non-null   str
 15  furnished                   6812 non-null   float64
 16  has_garage                  5006 non-null   float64
 17  parking_count               3796 non-null   float64
 18  kitchen_equipped            3009 non-null   str
 19  has_elevator                8160 non-null   float64
 20  facades                     8614 non-null   float64
 21  floors_total                5144 non-null   float64
 22  has_garden                  8287 non-null   float64
 23  garden_area_m2              2517 non-null   float64
 24  has_terrace                 9075 non-null   float64
 25  total_area_m2               6352 non-null   float64
 26  epc_score                   9623 non-null   str
 27  region                      11501 non-null  str
 28  province                    11501 non-null  str
 29  nearby_city                 11499 non-null  str
 30  km_from_nearby_city         11499 non-null  float64
 31  is_nearby_city_prestigious  11499 non-null  float64
 32  floor_number                3312 non-null   float64
 33  property_url                11501 non-null  str
dtypes: float64(20), int64(1), str(13)
memory usage: 3.0 MB

In [36]:
# First & last 3 rows
print("--- HEAD ---")
display(df_immovlan.head(3))
print("\n--- TAIL ---")
display(df_immovlan.tail(3))

--- HEAD ---

,property_id,property_type,property_subtype,price,price_type,living_area_m2,bedrooms,bathrooms,address,postal_code,...,has_terrace,total_area_m2,epc_score,region,province,nearby_city,km_from_nearby_city,is_nearby_city_prestigious,floor_number,property_url
0,https://immovlan.be/en/detail/residence/for-sa...,House,residence,550000.00,sell,250.00,4.00,1.00,Rue des Nonnes 32A,4400,...,1.00,780.00,A+,Wallonia,Liège,Liège,11.80,0.00,NaN,https://immovlan.be/en/detail/residence/for-sa...
1,https://immovlan.be/en/detail/apartment/for-sa...,Apartment,apartment,200000.00,sell,57.00,1.00,1.00,Avenue Louise 32A,1050,...,1.00,NaN,B,Brussels,Brussels Capital Region,Bruxelles,1.80,0.00,2.00,https://immovlan.be/en/detail/apartment/for-sa...
2,https://immovlan.be/en/detail/duplex/for-sale/...,Apartment,duplex,189000.00,sell,115.00,1.00,1.00,NaN,7500,...,1.00,NaN,G,Wallonia,Hainaut,Tournai,0.10,0.00,NaN,https://immovlan.be/en/detail/duplex/for-sale/...

--- TAIL ---

,property_id,property_type,property_subtype,price,price_type,living_area_m2,bedrooms,bathrooms,address,postal_code,...,has_terrace,total_area_m2,epc_score,region,province,nearby_city,km_from_nearby_city,is_nearby_city_prestigious,floor_number,property_url
11498,https://immovlan.be/en/detail/residence/for-sa...,House,residence,320000.00,sell,220.00,5.00,NaN,Rue des Quatre Arbres 11,5170,...,0.00,856.00,D,Wallonia,Namur,Namur,10.10,0.00,NaN,https://immovlan.be/en/detail/residence/for-sa...
11499,https://immovlan.be/en/detail/studio/for-sale/...,Apartment,studio,153000.00,sell,13.00,NaN,1.00,Rue André Masquelier 11,7000,...,NaN,NaN,NaN,Wallonia,Hainaut,Mons,0.70,0.00,0.00,https://immovlan.be/en/detail/studio/for-sale/...
11500,https://immovlan.be/en/detail/residence/for-sa...,House,residence,535000.00,sell,177.00,4.00,2.00,Spijkstraat 91-93,9000,...,1.00,155.00,NaN,Flanders,East Flanders,Gent,1.90,0.00,NaN,https://immovlan.be/en/detail/residence/for-sa...

In [37]:
# Summary statistics
df_immovlan.describe(include='all')

,property_id,property_type,property_subtype,price,price_type,living_area_m2,bedrooms,bathrooms,address,postal_code,...,has_terrace,total_area_m2,epc_score,region,province,nearby_city,km_from_nearby_city,is_nearby_city_prestigious,floor_number,property_url
count,11501,11501,11501,11292.00,11501,10707.00,11090.00,10203.00,9299,11501.00,...,9075.00,6352.00,9623,11501,11501,11499,11499.00,11499.00,3312.00,11501
unique,11500,2,15,NaN,1,NaN,NaN,NaN,8744,NaN,...,NaN,NaN,12,3,9,42,NaN,NaN,NaN,11500
top,https://immovlan.be/en/detail/residence/for-sa...,House,residence,NaN,sell,NaN,NaN,NaN,Dessauerplein 1,NaN,...,NaN,NaN,C,Wallonia,Liège,Liège,NaN,NaN,NaN,https://immovlan.be/en/detail/residence/for-sa...
freq,2,7406,6015,NaN,11501,NaN,NaN,NaN,31,NaN,...,NaN,NaN,1872,5582,1734,1299,NaN,NaN,NaN,2
mean,NaN,NaN,NaN,388215.93,NaN,173.37,3.07,1.40,NaN,5269.59,...,0.82,1646.79,NaN,NaN,NaN,NaN,37.20,0.05,3.61,NaN
std,NaN,NaN,NaN,357484.06,NaN,160.29,2.18,0.98,NaN,2621.05,...,0.38,5464.68,NaN,NaN,NaN,NaN,403.64,0.22,30.11,NaN
min,NaN,NaN,NaN,1.00,NaN,1.00,1.00,1.00,NaN,1000.00,...,0.00,2.00,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN
25%,NaN,NaN,NaN,190000.00,NaN,90.00,2.00,1.00,NaN,3500.00,...,1.00,260.00,NaN,NaN,NaN,NaN,3.10,0.00,1.00,NaN
50%,NaN,NaN,NaN,299000.00,NaN,143.00,3.00,1.00,NaN,5190.00,...,1.00,626.00,NaN,NaN,NaN,NaN,8.30,0.00,2.00,NaN
75%,NaN,NaN,NaN,495000.00,NaN,206.00,4.00,2.00,NaN,7370.00,...,1.00,1338.50,NaN,NaN,NaN,NaN,16.90,0.00,3.00,NaN
max,NaN,NaN,NaN,13000000.00,NaN,3990.00,100.00,23.00,NaN,9991.00,...,1.00,178367.00,NaN,NaN,NaN,NaN,6681.30,1.00,999.00,NaN

**copy the dataset before applying any change**

In [148]:
df_immo = df_immovlan.copy()

In [149]:
columns_to_control = ['living_area_m2', 'total_area_m2','price']
suspect_vals_cols = ['bathrooms', 'bedrooms', 'floor_number']
for suspect in suspect_vals_cols:
    if suspect == 'bathrooms':
        cond = (df_immo['bathrooms'] > 5.00)
    elif suspect == 'bedrooms':
        cond = (df_immo['bedrooms'] > 5.00)
    else:
        cond = (df_immo['floor_number'] == 999.00)

    print(f"Property url: {df_immo.loc[cond, 'property_url']}")

Property url: 109      https://immovlan.be/en/detail/residence/for-sa...
142      https://immovlan.be/en/detail/mixed-building/f...
157      https://immovlan.be/en/detail/mixed-building/f...
163      https://immovlan.be/en/detail/residence/for-sa...
194      https://immovlan.be/en/detail/residence/for-sa...
                               ...
11388    https://immovlan.be/en/detail/mixed-building/f...
11415    https://immovlan.be/en/detail/residence/for-sa...
11420    https://immovlan.be/en/detail/residence/for-sa...
11439    https://immovlan.be/en/detail/residence/for-sa...
11474    https://immovlan.be/en/detail/residence/for-sa...
Name: property_url, Length: 86, dtype: str
Property url: 7        https://immovlan.be/en/detail/mixed-building/f...
15       https://immovlan.be/en/detail/residence/for-sa...
55       https://immovlan.be/en/detail/residence/for-sa...
86       https://immovlan.be/en/detail/residence/for-sa...
90       https://immovlan.be/en/detail/residence/for-sa...
                               ...
11439    https://immovlan.be/en/detail/residence/for-sa...
11459    https://immovlan.be/en/detail/residence/for-sa...
11470    https://immovlan.be/en/detail/residence/for-sa...
11474    https://immovlan.be/en/detail/residence/for-sa...
11497    https://immovlan.be/en/detail/master-house/for...
Name: property_url, Length: 598, dtype: str
Property url: 735     https://immovlan.be/en/detail/apartment/for-sa...
3314    https://immovlan.be/en/detail/apartment/for-sa...
7262    https://immovlan.be/en/detail/apartment/for-sa...
Name: property_url, dtype: str

In [150]:
# printing temporary df

condition = (df_immo['bathrooms'] > 5.00)
df_immo_target = df_immo[condition].sort_values(by='bathrooms', ascending=False)

indexes_to_be_deleted = df_immo_target[df_immo_target['price'].isna()].index.tolist()
print(indexes_to_be_deleted)

df_immo_to_print = df_immo_target[df_immo_target['price'].notna()]

df_immo_to_print.loc[condition, ['bathrooms'] + columns_to_control]

[8004, 4813, 2188, 9806, 7690]

       bathrooms  living_area_m2  total_area_m2      price
604        23.00         1280.00       10808.00  990000.00
8303       22.00         1498.00            NaN 4950000.00
9648       15.00          560.00        1084.00  340000.00
3932       14.00             NaN            NaN  750000.00
9111       14.00          600.00       11050.00 2300000.00
...          ...             ...            ...        ...
9493        6.00          204.00            NaN  475000.00
10721       6.00          230.00        1025.00  360000.00
10943       6.00          558.00        1506.00  450000.00
11415       6.00          317.00         166.00  575000.00
11439       6.00          600.00         811.00  530000.00

[81 rows x 4 columns]

In [151]:

# printing values in columns_to_control for each row and deleting rows with NaN price

for index, row in df_immo_to_print.iterrows():
    print(f"property with {row['bathrooms']} in 'bathrooms' column (Index: {index}) has:\n")
    for column in columns_to_control:
        print(f"  {row[column]} in {column}.\n")

# deletion of found rows with NaN price value
df_immo.drop(indexes_to_be_deleted)
deleted_indexes = ", ".join(map(str, indexes_to_be_deleted))
print(f'Rows with labels {deleted_indexes} with NaN price habe been successfully deleted.')

property with 23.0 in 'bathrooms' column (Index: 604) has:

  1280.0 in living_area_m2.

  10808.0 in total_area_m2.

  990000.0 in price.

property with 22.0 in 'bathrooms' column (Index: 8303) has:

  1498.0 in living_area_m2.

  nan in total_area_m2.

  4950000.0 in price.

property with 15.0 in 'bathrooms' column (Index: 9648) has:

  560.0 in living_area_m2.

  1084.0 in total_area_m2.

  340000.0 in price.

property with 14.0 in 'bathrooms' column (Index: 3932) has:

  nan in living_area_m2.

  nan in total_area_m2.

  750000.0 in price.

property with 14.0 in 'bathrooms' column (Index: 9111) has:

  600.0 in living_area_m2.

  11050.0 in total_area_m2.

  2300000.0 in price.

property with 14.0 in 'bathrooms' column (Index: 5774) has:

  1100.0 in living_area_m2.

  1172.0 in total_area_m2.

  550000.0 in price.

property with 14.0 in 'bathrooms' column (Index: 11388) has:

  391.0 in living_area_m2.

  459.0 in total_area_m2.

  790000.0 in price.

property with 12.0 in 'bathrooms' column (Index: 5052) has:

  815.0 in living_area_m2.

  310.0 in total_area_m2.

  2700000.0 in price.

property with 12.0 in 'bathrooms' column (Index: 495) has:

  600.0 in living_area_m2.

  907.0 in total_area_m2.

  698000.0 in price.

property with 12.0 in 'bathrooms' column (Index: 904) has:

  nan in living_area_m2.

  2518.0 in total_area_m2.

  950000.0 in price.

property with 12.0 in 'bathrooms' column (Index: 7026) has:

  850.0 in living_area_m2.

  nan in total_area_m2.

  2919475.0 in price.

property with 11.0 in 'bathrooms' column (Index: 7601) has:

  535.0 in living_area_m2.

  210.0 in total_area_m2.

  599000.0 in price.

property with 11.0 in 'bathrooms' column (Index: 7780) has:

  570.0 in living_area_m2.

  2668.0 in total_area_m2.

  1340000.0 in price.

property with 11.0 in 'bathrooms' column (Index: 8781) has:

  502.0 in living_area_m2.

  3582.0 in total_area_m2.

  780000.0 in price.

property with 11.0 in 'bathrooms' column (Index: 7616) has:

  110.0 in living_area_m2.

  105.0 in total_area_m2.

  179000.0 in price.

property with 11.0 in 'bathrooms' column (Index: 4913) has:

  434.0 in living_area_m2.

  350.0 in total_area_m2.

  495000.0 in price.

property with 10.0 in 'bathrooms' column (Index: 4062) has:

  440.0 in living_area_m2.

  162.0 in total_area_m2.

  695000.0 in price.

property with 10.0 in 'bathrooms' column (Index: 296) has:

  579.0 in living_area_m2.

  3621.0 in total_area_m2.

  975000.0 in price.

property with 10.0 in 'bathrooms' column (Index: 632) has:

  700.0 in living_area_m2.

  3020.0 in total_area_m2.

  650000.0 in price.

property with 10.0 in 'bathrooms' column (Index: 10053) has:

  400.0 in living_area_m2.

  3621.0 in total_area_m2.

  975000.0 in price.

property with 10.0 in 'bathrooms' column (Index: 5173) has:

  569.0 in living_area_m2.

  1398.0 in total_area_m2.

  275000.0 in price.

property with 10.0 in 'bathrooms' column (Index: 3061) has:

  900.0 in living_area_m2.

  5845.0 in total_area_m2.

  1350000.0 in price.

property with 9.0 in 'bathrooms' column (Index: 194) has:

  1300.0 in living_area_m2.

  13581.0 in total_area_m2.

  1500000.0 in price.

property with 9.0 in 'bathrooms' column (Index: 1982) has:

  530.0 in living_area_m2.

  16069.0 in total_area_m2.

  695000.0 in price.

property with 9.0 in 'bathrooms' column (Index: 9107) has:

  245.0 in living_area_m2.

  140.0 in total_area_m2.

  507700.0 in price.

property with 9.0 in 'bathrooms' column (Index: 8907) has:

  700.0 in living_area_m2.

  1114.0 in total_area_m2.

  995000.0 in price.

property with 9.0 in 'bathrooms' column (Index: 9659) has:

  541.0 in living_area_m2.

  236.0 in total_area_m2.

  1050000.0 in price.

property with 9.0 in 'bathrooms' column (Index: 163) has:

  545.0 in living_area_m2.

  2477.0 in total_area_m2.

  1385000.0 in price.

property with 8.0 in 'bathrooms' column (Index: 7196) has:

  800.0 in living_area_m2.

  26978.0 in total_area_m2.

  2495000.0 in price.

property with 8.0 in 'bathrooms' column (Index: 4585) has:

  400.0 in living_area_m2.

  4545.0 in total_area_m2.

  1450000.0 in price.

property with 8.0 in 'bathrooms' column (Index: 9301) has:

  570.0 in living_area_m2.

  5000.0 in total_area_m2.

  975000.0 in price.

property with 8.0 in 'bathrooms' column (Index: 109) has:

  304.0 in living_area_m2.

  nan in total_area_m2.

  569000.0 in price.

property with 8.0 in 'bathrooms' column (Index: 1725) has:

  991.0 in living_area_m2.

  4673.0 in total_area_m2.

  2500000.0 in price.

property with 8.0 in 'bathrooms' column (Index: 462) has:

  534.0 in living_area_m2.

  8694.0 in total_area_m2.

  1200000.0 in price.

property with 8.0 in 'bathrooms' column (Index: 11301) has:

  750.0 in living_area_m2.

  1846.0 in total_area_m2.

  1700000.0 in price.

property with 8.0 in 'bathrooms' column (Index: 4830) has:

  250.0 in living_area_m2.

  250.0 in total_area_m2.

  599000.0 in price.

property with 8.0 in 'bathrooms' column (Index: 1907) has:

  505.0 in living_area_m2.

  4300.0 in total_area_m2.

  547000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 10609) has:

  342.0 in living_area_m2.

  3677.0 in total_area_m2.

  429000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 4507) has:

  450.0 in living_area_m2.

  2202.0 in total_area_m2.

  1195000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 11420) has:

  585.0 in living_area_m2.

  11600.0 in total_area_m2.

  1275000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 11474) has:

  750.0 in living_area_m2.

  2665.0 in total_area_m2.

  995000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 9401) has:

  234.0 in living_area_m2.

  81.0 in total_area_m2.

  600000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 5250) has:

  462.0 in living_area_m2.

  13788.0 in total_area_m2.

  1490000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 8326) has:

  483.0 in living_area_m2.

  315.0 in total_area_m2.

  849000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 202) has:

  500.0 in living_area_m2.

  nan in total_area_m2.

  1701000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 157) has:

  450.0 in living_area_m2.

  275.0 in total_area_m2.

  990000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 7159) has:

  1270.0 in living_area_m2.

  65000.0 in total_area_m2.

  1995000.0 in price.

property with 7.0 in 'bathrooms' column (Index: 5679) has:

  535.0 in living_area_m2.

  9970.0 in total_area_m2.

  3900000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 373) has:

  800.0 in living_area_m2.

  7600.0 in total_area_m2.

  1895000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 142) has:

  472.0 in living_area_m2.

  252.0 in total_area_m2.

  1495000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 1723) has:

  710.0 in living_area_m2.

  nan in total_area_m2.

  799000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 1647) has:

  1000.0 in living_area_m2.

  7801.0 in total_area_m2.

  1495000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 1523) has:

  806.0 in living_area_m2.

  2600.0 in total_area_m2.

  780000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 1522) has:

  525.0 in living_area_m2.

  345.0 in total_area_m2.

  1440000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 1076) has:

  1120.0 in living_area_m2.

  14065.0 in total_area_m2.

  1690000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 1259) has:

  700.0 in living_area_m2.

  36525.0 in total_area_m2.

  850000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 1055) has:

  300.0 in living_area_m2.

  1778.0 in total_area_m2.

  525000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 277) has:

  250.0 in living_area_m2.

  100.0 in total_area_m2.

  595000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 3010) has:

  115.0 in living_area_m2.

  339.0 in total_area_m2.

  100000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 2095) has:

  404.0 in living_area_m2.

  5990.0 in total_area_m2.

  569000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 1768) has:

  754.0 in living_area_m2.

  1331.0 in total_area_m2.

  1259000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 5812) has:

  470.0 in living_area_m2.

  744.0 in total_area_m2.

  1295000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 5244) has:

  556.0 in living_area_m2.

  10000.0 in total_area_m2.

  980000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 5133) has:

  512.0 in living_area_m2.

  472.0 in total_area_m2.

  745000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 4150) has:

  444.0 in living_area_m2.

  245.0 in total_area_m2.

  2200000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 4089) has:

  300.0 in living_area_m2.

  nan in total_area_m2.

  495000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 6066) has:

  550.0 in living_area_m2.

  1880.0 in total_area_m2.

  1285000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 6211) has:

  759.0 in living_area_m2.

  345.0 in total_area_m2.

  3650000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 9005) has:

  670.0 in living_area_m2.

  1543.0 in total_area_m2.

  998000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 7731) has:

  910.0 in living_area_m2.

  570.0 in total_area_m2.

  695000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 8357) has:

  500.0 in living_area_m2.

  nan in total_area_m2.

  1550000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 8590) has:

  562.0 in living_area_m2.

  646.0 in total_area_m2.

  1195000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 8659) has:

  228.0 in living_area_m2.

  101.0 in total_area_m2.

  325000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 8867) has:

  497.0 in living_area_m2.

  nan in total_area_m2.

  740000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 9918) has:

  nan in living_area_m2.

  3030.0 in total_area_m2.

  985000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 9555) has:

  700.0 in living_area_m2.

  89392.0 in total_area_m2.

  880000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 9493) has:

  204.0 in living_area_m2.

  nan in total_area_m2.

  475000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 10721) has:

  230.0 in living_area_m2.

  1025.0 in total_area_m2.

  360000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 10943) has:

  558.0 in living_area_m2.

  1506.0 in total_area_m2.

  450000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 11415) has:

  317.0 in living_area_m2.

  166.0 in total_area_m2.

  575000.0 in price.

property with 6.0 in 'bathrooms' column (Index: 11439) has:

  600.0 in living_area_m2.

  811.0 in total_area_m2.

  530000.0 in price.

Rows with labels 8004, 4813, 2188, 9806, 7690 with NaN price habe been successfully deleted.

*deletion of row 604 to be considered*

In [152]:
print(f"property with {df_immo['bedrooms'].max()} in 'bedrooms' column:")
df_immo.loc[(df_immo['bedrooms'] == 100.00), ['living_area_m2', 'total_area_m2', 'bedrooms','price']]

property with 100.0 in 'bedrooms' column:

      living_area_m2  total_area_m2  bedrooms       price
5214             NaN            NaN    100.00 13000000.00

**deliting row 5214**

In [153]:
to_be_deleted = [5214]
deleted_indexes = ", ".join(map(str, to_be_deleted))
df_immo = df_immo.drop(to_be_deleted)
print(f'Rows with labels {deleted_indexes} successfully deleted.')

Rows with labels 5214 successfully deleted.

**assessing other rows situation that have high value of bedrooms**

In [154]:
# printing temporary df

condition = (df_immo['bedrooms'] > 5.00)
df_immo_target = df_immo[condition].sort_values(by='bedrooms', ascending=False)

indexes_to_be_deleted = df_immo_target[df_immo_target['price'].isna()].index.tolist()
print(indexes_to_be_deleted)

df_immo_to_print = df_immo_target[df_immo_target['price'].notna()]

df_immo_to_print.loc[condition, ['bedrooms'] + columns_to_control]

[4813, 8004, 3831, 11276, 2188, 5613, 2176, 5818, 8192, 5059, 2941, 7690, 2221, 9806, 928, 5519, 6141, 6580, 3523, 3305, 9236, 9154]

       bedrooms  living_area_m2  total_area_m2      price
3081      63.00         2378.00        1232.00  650000.00
6056      50.00         3990.00        2495.00 1988750.00
1556      50.00         3500.00       33704.00 1400000.00
2797      41.00             NaN        6000.00 1499000.00
586       32.00          840.00        1017.00  795000.00
...         ...             ...            ...        ...
11049      6.00          299.00         300.00  545000.00
11034      6.00          369.00         521.00  549950.00
11032      6.00          280.00         408.00  525000.00
11008      6.00          294.00         423.00  465000.00
11000      6.00          281.00         930.00  327000.00

[575 rows x 4 columns]

In [155]:
# printing values in columns_to_control for each row and deleting rows with NaN price

for index, row in df_immo_to_print.iterrows():
    print(f"property with {row['bedrooms']} in 'bedrooms' column (Index: {index}) has:\n")
    for column in columns_to_control:
        print(f"  {row[column]} in {column}.\n")

# deletion of found rows with NaN price value
df_immo.drop(indexes_to_be_deleted)
deleted_indexes = ", ".join(map(str, indexes_to_be_deleted))
print(f'Rows with labels {deleted_indexes} with NaN price habe been successfully deleted.')

property with 63.0 in 'bedrooms' column (Index: 3081) has:

  2378.0 in living_area_m2.

  1232.0 in total_area_m2.

  650000.0 in price.

property with 50.0 in 'bedrooms' column (Index: 6056) has:

  3990.0 in living_area_m2.

  2495.0 in total_area_m2.

  1988750.0 in price.

property with 50.0 in 'bedrooms' column (Index: 1556) has:

  3500.0 in living_area_m2.

  33704.0 in total_area_m2.

  1400000.0 in price.

property with 41.0 in 'bedrooms' column (Index: 2797) has:

  nan in living_area_m2.

  6000.0 in total_area_m2.

  1499000.0 in price.

property with 32.0 in 'bedrooms' column (Index: 586) has:

  840.0 in living_area_m2.

  1017.0 in total_area_m2.

  795000.0 in price.

property with 30.0 in 'bedrooms' column (Index: 358) has:

  3000.0 in living_area_m2.

  14229.0 in total_area_m2.

  1350000.0 in price.

property with 30.0 in 'bedrooms' column (Index: 8876) has:

  1380.0 in living_area_m2.

  6149.0 in total_area_m2.

  950000.0 in price.

property with 26.0 in 'bedrooms' column (Index: 604) has:

  1280.0 in living_area_m2.

  10808.0 in total_area_m2.

  990000.0 in price.

property with 25.0 in 'bedrooms' column (Index: 1076) has:

  1120.0 in living_area_m2.

  14065.0 in total_area_m2.

  1690000.0 in price.

property with 25.0 in 'bedrooms' column (Index: 9096) has:

  nan in living_area_m2.

  nan in total_area_m2.

  7750000.0 in price.

property with 24.0 in 'bedrooms' column (Index: 8303) has:

  1498.0 in living_area_m2.

  nan in total_area_m2.

  4950000.0 in price.

property with 24.0 in 'bedrooms' column (Index: 7997) has:

  1500.0 in living_area_m2.

  nan in total_area_m2.

  1070000.0 in price.

property with 24.0 in 'bedrooms' column (Index: 7026) has:

  850.0 in living_area_m2.

  nan in total_area_m2.

  2919475.0 in price.

property with 22.0 in 'bedrooms' column (Index: 904) has:

  nan in living_area_m2.

  2518.0 in total_area_m2.

  950000.0 in price.

property with 21.0 in 'bedrooms' column (Index: 7105) has:

  1565.0 in living_area_m2.

  27811.0 in total_area_m2.

  1800000.0 in price.

property with 19.0 in 'bedrooms' column (Index: 194) has:

  1300.0 in living_area_m2.

  13581.0 in total_area_m2.

  1500000.0 in price.

property with 19.0 in 'bedrooms' column (Index: 8940) has:

  700.0 in living_area_m2.

  171.0 in total_area_m2.

  299900.0 in price.

property with 18.0 in 'bedrooms' column (Index: 7) has:

  800.0 in living_area_m2.

  419.0 in total_area_m2.

  650000.0 in price.

property with 18.0 in 'bedrooms' column (Index: 1013) has:

  820.0 in living_area_m2.

  nan in total_area_m2.

  1480000.0 in price.

property with 17.0 in 'bedrooms' column (Index: 6393) has:

  nan in living_area_m2.

  1316.0 in total_area_m2.

  299000.0 in price.

property with 17.0 in 'bedrooms' column (Index: 3725) has:

  nan in living_area_m2.

  nan in total_area_m2.

  2399000.0 in price.

property with 17.0 in 'bedrooms' column (Index: 5052) has:

  815.0 in living_area_m2.

  310.0 in total_area_m2.

  2700000.0 in price.

property with 16.0 in 'bedrooms' column (Index: 1259) has:

  700.0 in living_area_m2.

  36525.0 in total_area_m2.

  850000.0 in price.

property with 16.0 in 'bedrooms' column (Index: 5774) has:

  1100.0 in living_area_m2.

  1172.0 in total_area_m2.

  550000.0 in price.

property with 15.0 in 'bedrooms' column (Index: 9648) has:

  560.0 in living_area_m2.

  1084.0 in total_area_m2.

  340000.0 in price.

property with 15.0 in 'bedrooms' column (Index: 4383) has:

  nan in living_area_m2.

  nan in total_area_m2.

  995000.0 in price.

property with 15.0 in 'bedrooms' column (Index: 8541) has:

  nan in living_area_m2.

  nan in total_area_m2.

  2600000.0 in price.

property with 15.0 in 'bedrooms' column (Index: 3920) has:

  nan in living_area_m2.

  nan in total_area_m2.

  1450000.0 in price.

property with 15.0 in 'bedrooms' column (Index: 3061) has:

  900.0 in living_area_m2.

  5845.0 in total_area_m2.

  1350000.0 in price.

property with 15.0 in 'bedrooms' column (Index: 11301) has:

  750.0 in living_area_m2.

  1846.0 in total_area_m2.

  1700000.0 in price.

property with 15.0 in 'bedrooms' column (Index: 11383) has:

  nan in living_area_m2.

  nan in total_area_m2.

  850000.0 in price.

property with 14.0 in 'bedrooms' column (Index: 4772) has:

  nan in living_area_m2.

  nan in total_area_m2.

  530000.0 in price.

property with 14.0 in 'bedrooms' column (Index: 3932) has:

  nan in living_area_m2.

  nan in total_area_m2.

  750000.0 in price.

property with 14.0 in 'bedrooms' column (Index: 9111) has:

  600.0 in living_area_m2.

  11050.0 in total_area_m2.

  2300000.0 in price.

property with 14.0 in 'bedrooms' column (Index: 9918) has:

  nan in living_area_m2.

  3030.0 in total_area_m2.

  985000.0 in price.

property with 14.0 in 'bedrooms' column (Index: 8781) has:

  502.0 in living_area_m2.

  3582.0 in total_area_m2.

  780000.0 in price.

property with 14.0 in 'bedrooms' column (Index: 11388) has:

  391.0 in living_area_m2.

  459.0 in total_area_m2.

  790000.0 in price.

property with 13.0 in 'bedrooms' column (Index: 7780) has:

  570.0 in living_area_m2.

  2668.0 in total_area_m2.

  1340000.0 in price.

property with 13.0 in 'bedrooms' column (Index: 9555) has:

  700.0 in living_area_m2.

  89392.0 in total_area_m2.

  880000.0 in price.

property with 13.0 in 'bedrooms' column (Index: 5411) has:

  850.0 in living_area_m2.

  469.0 in total_area_m2.

  1975000.0 in price.

property with 12.0 in 'bedrooms' column (Index: 7180) has:

  300.0 in living_area_m2.

  897.0 in total_area_m2.

  250000.0 in price.

property with 12.0 in 'bedrooms' column (Index: 10898) has:

  514.0 in living_area_m2.

  631.0 in total_area_m2.

  350000.0 in price.

property with 12.0 in 'bedrooms' column (Index: 495) has:

  600.0 in living_area_m2.

  907.0 in total_area_m2.

  698000.0 in price.

property with 12.0 in 'bedrooms' column (Index: 6525) has:

  1066.0 in living_area_m2.

  nan in total_area_m2.

  200000.0 in price.

property with 12.0 in 'bedrooms' column (Index: 202) has:

  500.0 in living_area_m2.

  nan in total_area_m2.

  1701000.0 in price.

property with 12.0 in 'bedrooms' column (Index: 2293) has:

  620.0 in living_area_m2.

  890.0 in total_area_m2.

  600000.0 in price.

property with 12.0 in 'bedrooms' column (Index: 4571) has:

  600.0 in living_area_m2.

  nan in total_area_m2.

  1370000.0 in price.

property with 12.0 in 'bedrooms' column (Index: 11420) has:

  585.0 in living_area_m2.

  11600.0 in total_area_m2.

  1275000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 4062) has:

  440.0 in living_area_m2.

  162.0 in total_area_m2.

  695000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 7196) has:

  800.0 in living_area_m2.

  26978.0 in total_area_m2.

  2495000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 1982) has:

  530.0 in living_area_m2.

  16069.0 in total_area_m2.

  695000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 1608) has:

  600.0 in living_area_m2.

  898.0 in total_area_m2.

  540000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 7159) has:

  1270.0 in living_area_m2.

  65000.0 in total_area_m2.

  1995000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 2621) has:

  575.0 in living_area_m2.

  nan in total_area_m2.

  800000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 8357) has:

  500.0 in living_area_m2.

  nan in total_area_m2.

  1550000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 8577) has:

  150.0 in living_area_m2.

  2160.0 in total_area_m2.

  335000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 7601) has:

  535.0 in living_area_m2.

  210.0 in total_area_m2.

  599000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 4913) has:

  434.0 in living_area_m2.

  350.0 in total_area_m2.

  495000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 4585) has:

  400.0 in living_area_m2.

  4545.0 in total_area_m2.

  1450000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 1907) has:

  505.0 in living_area_m2.

  4300.0 in total_area_m2.

  547000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 4287) has:

  780.0 in living_area_m2.

  370.0 in total_area_m2.

  1290000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 11338) has:

  509.0 in living_area_m2.

  1270.0 in total_area_m2.

  939000.0 in price.

property with 11.0 in 'bedrooms' column (Index: 632) has:

  700.0 in living_area_m2.

  3020.0 in total_area_m2.

  650000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 9659) has:

  541.0 in living_area_m2.

  236.0 in total_area_m2.

  1050000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 296) has:

  579.0 in living_area_m2.

  3621.0 in total_area_m2.

  975000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 11497) has:

  1000.0 in living_area_m2.

  398.0 in total_area_m2.

  598000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 1723) has:

  710.0 in living_area_m2.

  nan in total_area_m2.

  799000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 10053) has:

  400.0 in living_area_m2.

  3621.0 in total_area_m2.

  975000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 7350) has:

  391.0 in living_area_m2.

  270.0 in total_area_m2.

  299000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 10761) has:

  680.0 in living_area_m2.

  1449.0 in total_area_m2.

  1400000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 4778) has:

  2400.0 in living_area_m2.

  4699.0 in total_area_m2.

  995000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 1705) has:

  340.0 in living_area_m2.

  1164.0 in total_area_m2.

  375000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 655) has:

  281.0 in living_area_m2.

  680.0 in total_area_m2.

  1195000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 8326) has:

  483.0 in living_area_m2.

  315.0 in total_area_m2.

  849000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 3217) has:

  385.0 in living_area_m2.

  nan in total_area_m2.

  1299000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 211) has:

  600.0 in living_area_m2.

  523.0 in total_area_m2.

  650000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 7982) has:

  500.0 in living_area_m2.

  1250.0 in total_area_m2.

  355000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 7251) has:

  609.0 in living_area_m2.

  277.0 in total_area_m2.

  1295000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 7256) has:

  500.0 in living_area_m2.

  500.0 in total_area_m2.

  960000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 3233) has:

  365.0 in living_area_m2.

  380.0 in total_area_m2.

  120000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 4912) has:

  500.0 in living_area_m2.

  1395.0 in total_area_m2.

  520000.0 in price.

property with 10.0 in 'bedrooms' column (Index: 979) has:

  360.0 in living_area_m2.

  710.0 in total_area_m2.

  980000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 10681) has:

  680.0 in living_area_m2.

  nan in total_area_m2.

  1350000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 5625) has:

  412.0 in living_area_m2.

  1949.0 in total_area_m2.

  256000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 5651) has:

  569.0 in living_area_m2.

  3150.0 in total_area_m2.

  499000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 10698) has:

  266.0 in living_area_m2.

  194.0 in total_area_m2.

  499000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 5244) has:

  556.0 in living_area_m2.

  10000.0 in total_area_m2.

  980000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 8274) has:

  445.0 in living_area_m2.

  nan in total_area_m2.

  1975000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 8983) has:

  517.0 in living_area_m2.

  nan in total_area_m2.

  325000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 462) has:

  534.0 in living_area_m2.

  8694.0 in total_area_m2.

  1200000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 1725) has:

  991.0 in living_area_m2.

  4673.0 in total_area_m2.

  2500000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 9107) has:

  245.0 in living_area_m2.

  140.0 in total_area_m2.

  507700.0 in price.

property with 9.0 in 'bedrooms' column (Index: 594) has:

  391.0 in living_area_m2.

  408.0 in total_area_m2.

  399000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 6945) has:

  730.0 in living_area_m2.

  nan in total_area_m2.

  795000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 6698) has:

  670.0 in living_area_m2.

  6176.0 in total_area_m2.

  595000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 6284) has:

  404.0 in living_area_m2.

  385.0 in total_area_m2.

  485000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 997) has:

  270.0 in living_area_m2.

  97.0 in total_area_m2.

  480000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 1290) has:

  380.0 in living_area_m2.

  10715.0 in total_area_m2.

  395000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 4674) has:

  340.0 in living_area_m2.

  52809.0 in total_area_m2.

  1280000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 10051) has:

  375.0 in living_area_m2.

  2604.0 in total_area_m2.

  550000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 1522) has:

  525.0 in living_area_m2.

  345.0 in total_area_m2.

  1440000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 373) has:

  800.0 in living_area_m2.

  7600.0 in total_area_m2.

  1895000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 9081) has:

  615.0 in living_area_m2.

  40505.0 in total_area_m2.

  1750000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 4334) has:

  364.0 in living_area_m2.

  nan in total_area_m2.

  495000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 7442) has:

  nan in living_area_m2.

  nan in total_area_m2.

  750000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 7815) has:

  nan in living_area_m2.

  nan in total_area_m2.

  1745000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 9163) has:

  385.0 in living_area_m2.

  525.0 in total_area_m2.

  495000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 5209) has:

  300.0 in living_area_m2.

  nan in total_area_m2.

  525000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 3123) has:

  357.0 in living_area_m2.

  1189.0 in total_area_m2.

  370000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 3113) has:

  657.0 in living_area_m2.

  45357.0 in total_area_m2.

  1650000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 8187) has:

  376.0 in living_area_m2.

  1250.0 in total_area_m2.

  995000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 2660) has:

  1500.0 in living_area_m2.

  1095.0 in total_area_m2.

  895000.0 in price.

property with 9.0 in 'bedrooms' column (Index: 8932) has:

  nan in living_area_m2.

  4000.0 in total_area_m2.

  1300000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 150) has:

  550.0 in living_area_m2.

  nan in total_area_m2.

  880000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 10943) has:

  558.0 in living_area_m2.

  1506.0 in total_area_m2.

  450000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 5812) has:

  470.0 in living_area_m2.

  744.0 in total_area_m2.

  1295000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 109) has:

  304.0 in living_area_m2.

  nan in total_area_m2.

  569000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 4935) has:

  323.0 in living_area_m2.

  116.0 in total_area_m2.

  590000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 10190) has:

  nan in living_area_m2.

  57078.0 in total_area_m2.

  4200000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 10062) has:

  514.0 in living_area_m2.

  101895.0 in total_area_m2.

  1200000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 1093) has:

  999.0 in living_area_m2.

  15541.0 in total_area_m2.

  750000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 4841) has:

  400.0 in living_area_m2.

  1196.0 in total_area_m2.

  640000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 10374) has:

  363.0 in living_area_m2.

  511.0 in total_area_m2.

  720000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 10429) has:

  700.0 in living_area_m2.

  2307.0 in total_area_m2.

  625000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 10446) has:

  388.0 in living_area_m2.

  95775.0 in total_area_m2.

  915000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 1109) has:

  445.0 in living_area_m2.

  298.0 in total_area_m2.

  1075000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 4477) has:

  500.0 in living_area_m2.

  nan in total_area_m2.

  895000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 5903) has:

  318.0 in living_area_m2.

  nan in total_area_m2.

  780000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 9610) has:

  210.0 in living_area_m2.

  nan in total_area_m2.

  749000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 9707) has:

  372.0 in living_area_m2.

  6476.0 in total_area_m2.

  490000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 1101) has:

  550.0 in living_area_m2.

  896.0 in total_area_m2.

  890000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 4631) has:

  580.0 in living_area_m2.

  820.0 in total_area_m2.

  1895000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 932) has:

  nan in living_area_m2.

  310.0 in total_area_m2.

  765000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 4889) has:

  586.0 in living_area_m2.

  12015.0 in total_area_m2.

  712500.0 in price.

property with 8.0 in 'bedrooms' column (Index: 1768) has:

  754.0 in living_area_m2.

  1331.0 in total_area_m2.

  1259000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 4292) has:

  412.0 in living_area_m2.

  255.0 in total_area_m2.

  299000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 1546) has:

  233.0 in living_area_m2.

  79.0 in total_area_m2.

  220000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 6893) has:

  780.0 in living_area_m2.

  21770.0 in total_area_m2.

  1100000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 6906) has:

  851.0 in living_area_m2.

  3301.0 in total_area_m2.

  1150000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 4150) has:

  444.0 in living_area_m2.

  245.0 in total_area_m2.

  2200000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 4176) has:

  370.0 in living_area_m2.

  1061.0 in total_area_m2.

  480000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 4208) has:

  nan in living_area_m2.

  nan in total_area_m2.

  750000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 6219) has:

  900.0 in living_area_m2.

  34932.0 in total_area_m2.

  1150000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 1647) has:

  1000.0 in living_area_m2.

  7801.0 in total_area_m2.

  1495000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 9301) has:

  570.0 in living_area_m2.

  5000.0 in total_area_m2.

  975000.0 in price.

property with 8.0 in 'bedrooms' column (Index: 9388) has:

  326.0 in living_area_m2.

  nan in total_area_m2.

  399000.0 in price.


In [157]:
# floor_number outlier
print(f"property with {df_immo['floor_number'].max()} in {'floor_number'} column:")
condition = (df_immo['floor_number'] == 999.00)
df_immo_target = df_immo[condition]
indexes_to_be_manipulated = df_immo_target.index.tolist()

df_immo.loc[condition, ['floor_number'] + columns_to_control]

property with 999.0 in floor_number column:

      floor_number  living_area_m2  total_area_m2     price
735         999.00          176.00            NaN 979000.00
3314        999.00           84.00            NaN 159000.00
7262        999.00             NaN            NaN 279000.00

**rows 735, 3314 and 7262 contain valuable infos - I sobstitute the floor number with NaN**

In [159]:
# converting 999 to NaN

for row in indexes_to_be_manipulated:
    df_immo.loc[condition, 'floor_number'] = np.nan
print(f'Floor number in rows labels {indexes_to_be_manipulated} successfully substituted with NaN.')

Floor number in rows labels [735, 3314, 7262] successfully substituted with NaN.

**delete ALL THE OTHER ROWS with nan price**

In [161]:
indexes_to_be_deleted = df_immo[df_immo['price'].isna()].index.tolist()

df_immo.drop(indexes_to_be_deleted)
deleted_indexes = ", ".join(map(str, indexes_to_be_deleted))
print(f'Rows with labels {deleted_indexes} with NaN price habe been successfully deleted.')

Rows with labels 152, 160, 369, 397, 400, 493, 562, 673, 686, 692, 824, 847, 848, 873, 928, 1017, 1102, 1116, 1156, 1206, 1240, 1280, 1281, 1282, 1377, 1592, 1644, 1691, 1793, 1796, 1840, 1859, 1925, 1960, 1964, 2015, 2075, 2176, 2188, 2198, 2221, 2308, 2311, 2629, 2680, 2686, 2695, 2735, 2773, 2808, 2820, 2864, 2901, 2921, 2941, 2974, 3011, 3028, 3064, 3071, 3125, 3128, 3150, 3164, 3166, 3181, 3292, 3304, 3305, 3467, 3523, 3549, 3563, 3569, 3612, 3631, 3637, 3709, 3718, 3785, 3831, 3959, 3961, 4040, 4256, 4258, 4347, 4350, 4360, 4377, 4417, 4612, 4627, 4744, 4780, 4813, 4850, 4856, 4930, 5044, 5059, 5090, 5170, 5328, 5374, 5443, 5509, 5515, 5519, 5552, 5613, 5779, 5801, 5803, 5818, 5911, 5929, 5959, 6073, 6141, 6164, 6173, 6249, 6505, 6554, 6580, 6602, 6606, 6750, 6790, 6796, 6869, 6995, 7164, 7171, 7179, 7255, 7337, 7346, 7418, 7421, 7513, 7567, 7632, 7683, 7690, 7750, 7977, 8004, 8013, 8043, 8108, 8161, 8192, 8375, 8474, 8490, 8601, 8634, 8664, 8713, 8773, 8889, 8890, 8924, 8955, 8966, 9154, 9162, 9190, 9236, 9290, 9382, 9404, 9431, 9667, 9748, 9784, 9806, 9898, 9995, 10064, 10065, 10066, 10129, 10180, 10224, 10236, 10299, 10341, 10444, 10546, 10697, 10717, 10760, 10837, 10882, 10940, 11105, 11246, 11248, 11270, 11276, 11343, 11363, 11365, 11418, 11423, 11465 with NaN price habe been successfully deleted.

**look at describe again**

In [162]:
df_immo.describe(include='all')

,property_id,property_type,property_subtype,price,price_type,living_area_m2,bedrooms,bathrooms,address,postal_code,...,has_terrace,total_area_m2,epc_score,region,province,nearby_city,km_from_nearby_city,is_nearby_city_prestigious,floor_number,property_url
count,11500,11500,11500,11291.00,11500,10707.00,11089.00,10203.00,9299,11500.00,...,9075.00,6352.00,9623,11500,11500,11498,11498.00,11498.00,3309.00,11500
unique,11499,2,15,NaN,1,NaN,NaN,NaN,8744,NaN,...,NaN,NaN,12,3,9,42,NaN,NaN,NaN,11499
top,https://immovlan.be/en/detail/residence/for-sa...,House,residence,NaN,sell,NaN,NaN,NaN,Dessauerplein 1,NaN,...,NaN,NaN,C,Wallonia,Liège,Liège,NaN,NaN,NaN,https://immovlan.be/en/detail/residence/for-sa...
freq,2,7405,6014,NaN,11500,NaN,NaN,NaN,31,NaN,...,NaN,NaN,1872,5582,1734,1299,NaN,NaN,NaN,2
mean,NaN,NaN,NaN,387098.96,NaN,173.37,3.07,1.40,NaN,5269.97,...,0.82,1646.79,NaN,NaN,NaN,NaN,37.20,0.05,2.71,NaN
std,NaN,NaN,NaN,337218.93,NaN,160.29,1.97,0.98,NaN,2620.87,...,0.38,5464.68,NaN,NaN,NaN,NaN,403.66,0.22,2.81,NaN
min,NaN,NaN,NaN,1.00,NaN,1.00,1.00,1.00,NaN,1000.00,...,0.00,2.00,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN
25%,NaN,NaN,NaN,190000.00,NaN,90.00,2.00,1.00,NaN,3500.00,...,1.00,260.00,NaN,NaN,NaN,NaN,3.10,0.00,1.00,NaN
50%,NaN,NaN,NaN,299000.00,NaN,143.00,3.00,1.00,NaN,5190.00,...,1.00,626.00,NaN,NaN,NaN,NaN,8.30,0.00,2.00,NaN
75%,NaN,NaN,NaN,495000.00,NaN,206.00,4.00,2.00,NaN,7370.00,...,1.00,1338.50,NaN,NaN,NaN,NaN,16.90,0.00,3.00,NaN
max,NaN,NaN,NaN,8994000.00,NaN,3990.00,63.00,23.00,NaN,9991.00,...,1.00,178367.00,NaN,NaN,NaN,NaN,6681.30,1.00,26.00,NaN

**do the same exploratory work on rows which have the lowest price (ascending=True)**

**-------------------------------------------------------------------------------------------------------------**

In [27]:
# Missing values map
missing = df_immovlan.isnull().sum()
pct = (missing / len(df_immovlan) * 100).round(1)
pd.DataFrame({'count': missing, 'pct%': pct}).query('count > 0')

                            count  pct%
price                         209  1.80
living_area_m2                794  6.90
bedrooms                      411  3.60
bathrooms                    1298 11.30
address                      2202 19.10
latitude                        2  0.00
longitude                       2  0.00
building_year                4711 41.00
state_of_the_building        2682 23.30
furnished                    4689 40.80
has_garage                   6495 56.50
parking_count                7705 67.00
kitchen_equipped             8492 73.80
has_elevator                 3341 29.00
facades                      2887 25.10
floors_total                 6357 55.30
has_garden                   3214 27.90
garden_area_m2               8984 78.10
has_terrace                  2426 21.10
total_area_m2                5149 44.80
epc_score                    1878 16.30
nearby_city                     2  0.00
km_from_nearby_city             2  0.00
is_nearby_city_prestigious      2  0.00
floor_number                 8189 71.20

In [28]:
# Cardinality of categorical columns
for col in ['property_type', 'price', 'region']:
    print(f"{col}: {df_immovlan[col].nunique()} unique → {df_immovlan[col].unique()}")

property_type: 2 unique → <StringArray>
['House', 'Apartment']
Length: 2, dtype: str
price: 1763 unique → [550000. 200000. 189000. ... 692774. 390744. 448492.]
region: 3 unique → <StringArray>
['Wallonia', 'Brussels', 'Flanders']
Length: 3, dtype: str

**Checking data types**

In [29]:
# Data type and duplicates
print("Data types at the start:")
print(df_immovlan.dtypes)

Data types at the start:
property_id                       str
property_type                     str
property_subtype                  str
price                         float64
price_type                        str
                               ...
nearby_city                       str
km_from_nearby_city           float64
is_nearby_city_prestigious    float64
floor_number                  float64
property_url                      str
Length: 34, dtype: object

**Setting categories and checking again**

In [30]:
print(df_immovlan['region'].unique())

<StringArray>
['Wallonia', 'Brussels', 'Flanders']
Length: 3, dtype: str

In [31]:
df_immovlan['region'] = pd.Categorical(
    df_immovlan['region'],
    categories=df_immovlan['region'].unique(),
    ordered=False)

df_immovlan['property_type'] = pd.Categorical(
    df_immovlan['property_type'],
    categories=df_immovlan['property_type'].unique(),
    ordered=False)

df_immovlan['property_subtype'] = pd.Categorical(
    df_immovlan['property_subtype'],
    categories=df_immovlan['property_subtype'].unique(),
    ordered=False)

print("Data types after categorizing:")
print(df_immovlan.dtypes)

Data types after categorizing:
property_id                        str
property_type                 category
property_subtype              category
price                          float64
price_type                         str
                                ...
nearby_city                        str
km_from_nearby_city            float64
is_nearby_city_prestigious     float64
floor_number                   float64
property_url                       str
Length: 34, dtype: object

In [ ]:
# **Checking for duplicates**

In [66]:
print("Number of duplicate properties:")
print(df_immovlan.duplicated().sum())

Number of duplicate properties:
0

# **Investigate NaN data**

In [61]:
df_immov = df_immovlan.copy()

# printing proportion of missing data in decreasing order of percentage
# print((df_immov.isna().mean()* 100).sort_values(ascending=False))

# printing the columns names with highest values of nan %
filtrated_col = (
    df_immov.isna().mean()* 100).sort_values(ascending=False)[
    (df_immov.isna().mean()* 100).sort_values(ascending=False) > 2]
print("Columns with nan percentage higher than 2:")
print(filtrated_col)

Columns with nan percentage higher than 2:
garden_area_m2          78.11
kitchen_equipped        73.84
floor_number            71.20
parking_count           66.99
has_garage              56.47
floors_total            55.27
total_area_m2           44.77
building_year           40.96
furnished               40.77
has_elevator            29.05
has_garden              27.95
facades                 25.10
state_of_the_building   23.32
has_terrace             21.09
address                 19.15
epc_score               16.33
bathrooms               11.29
living_area_m2           6.90
bedrooms                 3.57
dtype: float64

In [65]:
# grouping data by "property_type" and checking again for nan %
grouped_nan_perc = df_immov['floor_number'].isna().groupby(df_immov['property_type']).mean() * 100
print(grouped_nan_perc)
print("-" * 30)
print("\n")
print(f'⚠️ "Apartment" type has {grouped_nan_perc.loc['Apartment'].round(2)} percent nan.')
print("Fill 'floor_number' with median or mode.")
print("\n")
print(f'⚠️ "House" type has {grouped_nan_perc.loc['Apartment'].round(2)} percent nan.')
print("No 'floor_number' data for this group.")

property_type
House       100.00
Apartment    19.12
Name: floor_number, dtype: float64
------------------------------


⚠️ "Apartment" type has 19.12 percent nan.
Fill 'floor_number' with median or mode.


⚠️ "House" type has 19.12 percent nan.
No 'floor_number' data for this group.

In [ ]:
# grouping data by "property_type" and checking again for nan %
grouped_nan_perc = df_immov['floor_number'].isna().groupby(df_immov['property_type']).mean() * 100
print(grouped_nan_perc)
print("-" * 30)
print("\n")
print(f'⚠️ "Apartment" type has {grouped_nan_perc.loc['Apartment'].round(2)} percent nan.')
print("Fill 'floor_number' with median ore mode.")
print("\n")
print(f'⚠️ "House" type has {grouped_nan_perc.loc['Apartment'].round(2)} percent nan.')
print("No 'floor_number' data for this group.")

# **Standardize string data**

In [38]:
# isolating string type columns
string_columns = df_immovlan.select_dtypes(include=['object'])

# go through these columns to check for unique values
for column in string_columns:
    print(f'Unique values in column {column}:')
    print(df_immovlan[column].unique())
    print("-" * 30)

Unique values in column property_id:
<StringArray>
[               'https://immovlan.be/en/detail/residence/for-sale/4400/flemalle/vbd65018',
                  'https://immovlan.be/en/detail/apartment/for-sale/1050/elsene/vbe35215',
                    'https://immovlan.be/en/detail/duplex/for-sale/7500/tournai/vbe33657',
                   'https://immovlan.be/en/detail/residence/for-sale/3941/eksel/rbv74485',
     'https://immovlan.be/en/detail/residence/for-sale/6980/la-roche-en-ardenne/vbe31485',
  'https://immovlan.be/en/detail/residence/for-sale/1200/sint-lambrechts-woluwe/vbe35271',
 'https://immovlan.be/en/detail/residence/for-sale/7160/chapelle-lez-herlaimont/vbd97558',
              'https://immovlan.be/en/detail/mixed-building/for-sale/5000/namur/vbc95048',
                   'https://immovlan.be/en/detail/bungalow/for-sale/6940/durbuy/vbd83323',
                  'https://immovlan.be/en/detail/villa/for-sale/3850/binderveld/rbw10337',
 ...
   'https://immovlan.be/en/detail/residence/for-sale/6061/montignies-sur-sambre/rbv73552',
                'https://immovlan.be/en/detail/apartment/for-sale/7700/mouscron/vbe18735',
      'https://immovlan.be/en/detail/residence/for-sale/6940/barvaux-sur-ourthe/vbe27139',
                   'https://immovlan.be/en/detail/apartment/for-sale/1180/ukkel/vbe33057',
                'https://immovlan.be/en/detail/residence/for-sale/8670/koksijde/rbw25606',
            'https://immovlan.be/en/detail/apartment/for-sale/9070/destelbergen/rbw25383',
                'https://immovlan.be/en/detail/master-house/for-sale/9600/ronse/rbv92906',
                  'https://immovlan.be/en/detail/residence/for-sale/5170/lustin/vbe12938',
                       'https://immovlan.be/en/detail/studio/for-sale/7000/mons/vbe36548',
                    'https://immovlan.be/en/detail/residence/for-sale/9000/gent/rbw20319']
Length: 11500, dtype: str
------------------------------
Unique values in column price_type:
<StringArray>
['sell']
Length: 1, dtype: str
------------------------------
Unique values in column address:
<StringArray>
[          'Rue des Nonnes 32A',            'Avenue Louise 32A',
                            nan,         'Kerkstraat 20 + 20/1',
          'Quartier de Lohan 1',         'Rue du Pont-Levis 52',
                'RUE PASTUR 49', 'Val meleye 30 LOT 4 747L pie',
           'Dennenbosstraat 32',      'Hutsepotstraat 196 0104',
 ...
             '57 Rue de Perwez',        'Rue Arthur Piroton 24',
             'Rue du Ponçay 26',              'Rue Grimard 237',
           'Route de Durbuy 23',                 'Berglaan 26A',
         'Panhuisstraat 18 002',            'Grote Markt 28/29',
     'Rue des Quatre Arbres 11',      'Rue André Masquelier 11']
Length: 8745, dtype: str
------------------------------
Unique values in column city:
<StringArray>
[               'flemalle',                  'elsene',
                 'tournai',                   'eksel',
     'la-roche-en-ardenne',  'sint-lambrechts-woluwe',
 'chapelle-lez-herlaimont',                   'namur',
                  'durbuy',              'binderveld',
 ...
                    'vivy',              'lambermont',
            'beveren-leie',                   'heron',
               'erquennes',                  'gierle',
                 'pessoux',                'masbourg',
             'saint-aubin',      'bourseigne-vieille']
Length: 1425, dtype: str
------------------------------
Unique values in column state_of_the_building:
<StringArray>
[               'New',             'Normal',          'Excellent',
    'To be renovated',                  nan,        'To renovate',
    'Fully renovated',         'To restore',        'To demolish',
 'Under construction']
Length: 10, dtype: str
------------------------------
Unique values in column kitchen_equipped:
<StringArray>
['Fully equipped', nan, 'Super equipped', 'Partially equipped',
 'Not equipped']
Length: 5, dtype: str
------------------------------
Unique values in column epc_score:
<StringArray>
['A+', 'B', 'G', nan, 'D', 'C', 'A', 'E', 'F', 'A++', 'B+', 'C+', 'E+']
Length: 13, dtype: str
------------------------------
Unique values in column province:
<StringArray>
[                  'Liège', 'Brussels Capital Region',
                 'Hainaut',                 'Limburg',
              'Luxembourg',                   'Namur',
           'East Flanders',                 'Antwerp',
           'West Flanders']
Length: 9, dtype: str
------------------------------
Unique values in column nearby_city:
<StringArray>
[             'Liège',          'Bruxelles',            'Tournai',
               'Genk',           'Verviers',        'La Louvière',
              'Namur',       'Sint-Truiden',               'Gent',
               'Mons',            'Malines',          'Charleroi',
               'Geel',          'Antwerpen',              'Alost',
          'Roeselare',           'Mouscron',              'Arlon',
            'Lokeren',       'Knokke-Heist',            'Hasselt',
           'Turnhout',           'Kortrijk',           'De Panne',
         'Maastricht',            'Ostende',              'Lille',
          'Eindhoven',              'Uccle',        'Dendermonde',
       'Sint-Niklaas',             'Bruges',            'Waregem',
              'Breda',             'Aachen',                  nan,
            'Louvain',         'Luxembourg',           'Tervuren',
              'Reims',          'Dunkerque', 'Rhode-Saint-Genèse',
           'Waterloo']
Length: 43, dtype: str
------------------------------
Unique values in column property_url:
<StringArray>
[               'https://immovlan.be/en/detail/residence/for-sale/4400/flemalle/vbd65018',
                  'https://immovlan.be/en/detail/apartment/for-sale/1050/elsene/vbe35215',
                    'https://immovlan.be/en/detail/duplex/for-sale/7500/tournai/vbe33657',
                   'https://immovlan.be/en/detail/residence/for-sale/3941/eksel/rbv74485',
     'https://immovlan.be/en/detail/residence/for-sale/6980/la-roche-en-ardenne/vbe31485',
  'https://immovlan.be/en/detail/residence/for-sale/1200/sint-lambrechts-woluwe/vbe35271',
 'https://immovlan.be/en/detail/residence/for-sale/7160/chapelle-lez-herlaimont/vbd97558',
              'https://immovlan.be/en/detail/mixed-building/for-sale/5000/namur/vbc95048',
                   'https://immovlan.be/en/detail/bungalow/for-sale/6940/durbuy/vbd83323',
                  'https://immovlan.be/en/detail/villa/for-sale/3850/binderveld/rbw10337',
 ...
   'https://immovlan.be/en/detail/residence/for-sale/6061/montignies-sur-sambre/rbv73552',
                'https://immovlan.be/en/detail/apartment/for-sale/7700/mouscron/vbe18735',
      'https://immovlan.be/en/detail/residence/for-sale/6940/barvaux-sur-ourthe/vbe27139',
                   'https://immovlan.be/en/detail/apartment/for-sale/1180/ukkel/vbe33057',
                'https://immovlan.be/en/detail/residence/for-sale/8670/koksijde/rbw25606',
            'https://immovlan.be/en/detail/apartment/for-sale/9070/destelbergen/rbw25383',
                'https://immovlan.be/en/detail/master-house/for-sale/9600/ronse/rbv92906',
                  'https://immovlan.be/en/detail/residence/for-sale/5170/lustin/vbe12938',
                       'https://immovlan.be/en/detail/studio/for-sale/7000/mons/vbe36548',
                    'https://immovlan.be/en/detail/residence/for-sale/9000/gent/rbw20319']
Length: 11500, dtype: str
------------------------------

***must check for blank spaces***